
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARAM_ID = 32;
  public static final int ASSIGN_OP = 33;
  public static final int DIVIDE = 45;
  public static final int GTEQ = 39;
  public static final int STRING_LITERAL = 27;
  public static final int MULT = 44;
  public static final int LTEQ = 37;
  public static final int SEMI = 8;
  public static final int INT = 50;
  public static final int MINUS = 43;
  public static final int REF = 24;
  public static final int AND = 47;
  public static final int NOT = 34;
  public static final int LT = 36;
  public static final int RPAR = 7;
  public static final int OR = 48;
  public static final int IN = 5;
  public static final int BOOL = 52;
  public static final int COMMA = 9;
  public static final int FI = 17;
  public static final int BEGIN = 3;
  public static final int REC_DECL = 12;
  public static final int IF = 16;
  public static final int VAR_DECL = 14;
  public static final int DOT = 31;
  public static final int EOF = 0;
  public static final int OD = 22;
  public static final int RETURN = 23;
  public static final int PROC_DECL = 13;
  public static final int TRUE = 29;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int LCURLY = 10;
  public static final int ADD = 42;
  public static final int NULL = 35;
  public static final int NEQ = 41;
  public static final int EQ = 40;
  public static final int NAME = 53;
  public static final int RCURLY = 11;
  public static final int ELSE = 19;
  public static final int WHILE = 20;
  public static final int FLOAT = 49;
  public static final int THEN = 18;
  public static final int END = 4;
  public static final int STRING = 51;
  public static final int LPAR = 6;
  public static final int FLOAT_LITERAL = 28;
  public static final int FALSE = 30;
  public static final int GT = 38;
  public static final int DEREF = 25;
  public static final int EXPONENT = 46;
  public static final int DO = 21;
  public static final int INT_LITERAL = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "BEGIN",
  "END",
  "IN",
  "LPAR",
  "RPAR",
  "SEMI",
  "COMMA",
  "LCURLY",
  "RCURLY",
  "REC_DECL",
  "PROC_DECL",
  "VAR_DECL",
  "NEW",
  "IF",
  "FI",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "OD",
  "RETURN",
  "REF",
  "DEREF",
  "INT_LITERAL",
  "STRING_LITERAL",
  "FLOAT_LITERAL",
  "TRUE",
  "FALSE",
  "DOT",
  "PARAM_ID",
  "ASSIGN_OP",
  "NOT",
  "NULL",
  "LT",
  "LTEQ",
  "GT",
  "GTEQ",
  "EQ",
  "NEQ",
  "ADD",
  "MINUS",
  "MULT",
  "DIVIDE",
  "EXPONENT",
  "AND",
  "OR",
  "FLOAT",
  "INT",
  "STRING",
  "BOOL",
  "NAME"
  };
}

