
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ARIT = 20;
  public static final int RELOP = 19;
  public static final int STRUCT = 5;
  public static final int WHILE = 11;
  public static final int END = 4;
  public static final int RETURN = 12;
  public static final int FI = 10;
  public static final int NAME = 24;
  public static final int LOGIC = 21;
  public static final int REF = 13;
  public static final int IF = 9;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 3;
  public static final int STRING_LITERAL = 16;
  public static final int INT_LITERAL = 15;
  public static final int EOF = 0;
  public static final int DEREF = 14;
  public static final int COMMENT = 18;
  public static final int DOT = 22;
  public static final int error = 1;
  public static final int PARAM_ID = 23;
  public static final int PROC = 6;
  public static final int NEW = 8;
  public static final int FLOAT_LITERAL = 17;
  public static final int VAR = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "BEGIN",
  "END",
  "STRUCT",
  "PROC",
  "VAR",
  "NEW",
  "IF",
  "FI",
  "WHILE",
  "RETURN",
  "REF",
  "DEREF",
  "INT_LITERAL",
  "STRING_LITERAL",
  "FLOAT_LITERAL",
  "COMMENT",
  "RELOP",
  "ARIT",
  "LOGIC",
  "DOT",
  "PARAM_ID",
  "NAME"
  };
}

